In [1]:
print("Hello world")

Hello world

In [2]:
# Using Pandas, load in the CSV files

In [3]:
import pandas as pd

In [4]:
books = pd.read_csv(r"data\03_Library Systembook.csv")
customers = pd.read_csv(r"data\03_Library SystemCustomers.csv")

In [5]:
books.head()

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID
0,1.0,Catcher in the Rye,"""20/02/2023""",25/02/2023,2 weeks,1.0
1,2.0,Lord of the rings the two towers,"""24/03/2023""",21/03/2023,2 weeks,2.0
2,3.0,Lord of the rings the return of the kind,"""29/03/2023""",25/03/2023,2 weeks,3.0
3,4.0,The hobbit,"""02/04/2023""",25/03/2023,2 weeks,4.0
4,5.0,Dune,"""02/04/2023""",25/03/2023,2 weeks,5.0

In [6]:
customers.head()

   Customer ID   Customer Name
0          1.0        Jane Doe
1          2.0      John Smith
2          3.0      Dan Reeves
3          NaN             NaN
4          5.0  William Holden

In [11]:
def fix_invalid_date(x):
    if x == "32/05/2023":
        return "31/05/2023"
    return x
books["Book checkout"] = books["Book checkout"].apply(fix_invalid_date)
books["Book checkout"] = books["Book checkout"].str.replace('"', '', regex=False)
books.head(20)

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID
0,1.0,Catcher in the Rye,20/02/2023,25/02/2023,14.0,1.0
1,2.0,Lord of the rings the two towers,24/03/2023,21/03/2023,14.0,2.0
2,3.0,Lord of the rings the return of the kind,29/03/2023,25/03/2023,14.0,3.0
3,4.0,The hobbit,02/04/2023,25/03/2023,14.0,4.0
4,5.0,Dune,02/04/2023,25/03/2023,14.0,5.0
5,6.0,Little Women,02/04/2023,01/05/2023,14.0,1.0
6,7.0,IT,10/04/2063,03/04/2023,14.0,6.0
7,8.0,Misery,15/04/2023,03/04/2023,14.0,7.0
8,9.0,Catch 22,15/04/2023,16/04/2023,14.0,7.0
9,10.0,Animal Farm,20/04/2023,24/04/2023,14.0,2.0
10,11.0,1984,23/04/2023,27/04/2023,14.0,8.0
11,12.0,Little Women,02/04/2023,01/05/2023,14.0,1.0
12,13.0,East of Eden,30/04/2023,05/05/2023,14.0,2.0
13,14.0,America Is in the Heart,01/05/2023,07/05/2023,14.0,3.0
14,15.0,Wuthering Heights,01/05/2023,10/05/2023,14.0,9.0
15,16.0,Dark Tales,15/05/2023,01/06/2023,14.0,2.0
16,17.0,The Bloody Chamber,31/05/2023,04/06/2023,14.0,3.0
17,18.0,Les Miserables,03/06/2023,07/06/2023,14.0,5.0
18,19.0,Dracula,10/06/2023,10/07/2023,14.0,10.0
19,20.0,Frankenstein,01/06/2023,20/06/2023,14.0,2.0

In [12]:
books["Days allowed to borrow"] = books["Days allowed to borrow"].map({
    "2 weeks": 14
})
books.head(20)

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID
0,1.0,Catcher in the Rye,20/02/2023,25/02/2023,NaN,1.0
1,2.0,Lord of the rings the two towers,24/03/2023,21/03/2023,NaN,2.0
2,3.0,Lord of the rings the return of the kind,29/03/2023,25/03/2023,NaN,3.0
3,4.0,The hobbit,02/04/2023,25/03/2023,NaN,4.0
4,5.0,Dune,02/04/2023,25/03/2023,NaN,5.0
5,6.0,Little Women,02/04/2023,01/05/2023,NaN,1.0
6,7.0,IT,10/04/2063,03/04/2023,NaN,6.0
7,8.0,Misery,15/04/2023,03/04/2023,NaN,7.0
8,9.0,Catch 22,15/04/2023,16/04/2023,NaN,7.0
9,10.0,Animal Farm,20/04/2023,24/04/2023,NaN,2.0
10,11.0,1984,23/04/2023,27/04/2023,NaN,8.0
11,12.0,Little Women,02/04/2023,01/05/2023,NaN,1.0
12,13.0,East of Eden,30/04/2023,05/05/2023,NaN,2.0
13,14.0,America Is in the Heart,01/05/2023,07/05/2023,NaN,3.0
14,15.0,Wuthering Heights,01/05/2023,10/05/2023,NaN,9.0
15,16.0,Dark Tales,15/05/2023,01/06/2023,NaN,2.0
16,17.0,The Bloody Chamber,31/05/2023,04/06/2023,NaN,3.0
17,18.0,Les Miserables,03/06/2023,07/06/2023,NaN,5.0
18,19.0,Dracula,10/06/2023,10/07/2023,NaN,10.0
19,20.0,Frankenstein,01/06/2023,20/06/2023,NaN,2.0

In [13]:

date_cols = ["Book checkout", "Book Returned"]
books[date_cols] = books[date_cols].apply(pd.to_datetime, dayfirst=True)
books.head()

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID
0,1.0,Catcher in the Rye,2023-02-20,2023-02-25,NaN,1.0
1,2.0,Lord of the rings the two towers,2023-03-24,2023-03-21,NaN,2.0
2,3.0,Lord of the rings the return of the kind,2023-03-29,2023-03-25,NaN,3.0
3,4.0,The hobbit,2023-04-02,2023-03-25,NaN,4.0
4,5.0,Dune,2023-04-02,2023-03-25,NaN,5.0

In [14]:
books = books.dropna(subset="Books")
books.head()

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID
0,1.0,Catcher in the Rye,2023-02-20,2023-02-25,NaN,1.0
1,2.0,Lord of the rings the two towers,2023-03-24,2023-03-21,NaN,2.0
2,3.0,Lord of the rings the return of the kind,2023-03-29,2023-03-25,NaN,3.0
3,4.0,The hobbit,2023-04-02,2023-03-25,NaN,4.0
4,5.0,Dune,2023-04-02,2023-03-25,NaN,5.0

In [ ]:
books["Days on Loan"] = (books["Book Returned"] - books["Book checkout"]).dt.days
books.head()

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID,Days on Loan
0,1.0,Catcher in the Rye,2023-02-20,2023-02-25,NaN,1.0,5
1,2.0,Lord of the rings the two towers,2023-03-24,2023-03-21,NaN,2.0,-3
2,3.0,Lord of the rings the return of the kind,2023-03-29,2023-03-25,NaN,3.0,-4
3,4.0,The hobbit,2023-04-02,2023-03-25,NaN,4.0,-8
4,5.0,Dune,2023-04-02,2023-03-25,NaN,5.0,-8

In [16]:
customers.dropna()
customers

   Customer ID     Customer Name
0          1.0          Jane Doe
1          2.0        John Smith
2          3.0        Dan Reeves
3          NaN               NaN
4          5.0    William Holden
5          6.0     Jaztyn Forest
6          7.0     Jackie Irving
7          8.0  Matthew Stirling
8          9.0         Emory Ted

In [17]:
customers_cleaned = customers.dropna()
customers_cleaned

   Customer ID     Customer Name
0          1.0          Jane Doe
1          2.0        John Smith
2          3.0        Dan Reeves
4          5.0    William Holden
5          6.0     Jaztyn Forest
6          7.0     Jackie Irving
7          8.0  Matthew Stirling
8          9.0         Emory Ted